name: White Paper
description: >
    description
about: >
    about

master_repo: false
url: "https://blog.unko.fun"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           unko
  avatar:         "https://avatars0.githubusercontent.com/u/11971487?s=460&u=256432881ba2af2392cdde58d1ee2db2f5c0bc16&v=4"
  email:          "840382477@qq.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: 
  github: https://github.com/AmyF
  stackexchange: 
  linkedin: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
